version: "3"
services:
  app:
    build: .
    ports:
      - "8888:8888"
      - "5000:5000"
    volumes:
      - .:/home/user
    environment:
      DISPLAY: host.docker.internal:0.0
    command: sleep infinity
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]